name: ShellCheck

on: [push, pull_request]

jobs:
  lint:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Find and run ShellCheck on all .sh files
        run: |
          shopt -s globstar
          files=(**/*.sh)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No shell script files to check."
            exit 0
          fi
          shellcheck -S error "${files[@]}"
