name: ShellCheck

on: [push, pull_request]

jobs:
  lint:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Run ShellCheck on .sh files
        run: shellcheck *.sh
